export default function About() {
  return (
    <>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
      <div className="bg-red-200">about</div>
    </>
  );
}
